CREATE TABLE company (
id int not null auto_increment primary key,
code varchar(50) not null,
name varchar(200) not null,
customer tinyint not null default 1,
supplier tinyint not null default 0,
memo text not null default '',
closed tinyint not null default 0,
vatCode varchar(50) not null default '',
regCode varchar(50) not null default '',
addrStreet1 varchar(50) not null default '',
addrStreet2 varchar(50) not null default '',
addrCity varchar(50) not null default '',
addrIndex varchar(50) not null default '',
addrCountry varchar(50) not null default '',
addr varchar(255) not null default '',
deliveryTerms varchar(100) not null default '',
paymentTerms varchar(100) not null default '',
contact varchar(50) not null default '',
phone varchar(50) not null default '',
email varchar(50) not null default '',
fax varchar(50) not null default '',
mdCreated datetime,
mdUpdated datetime,
mdCreatorId int,
mdUpdaterId int
) COMMENT='companies registry'
